name: continuous-integration-tests
on:
  push

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Path lister action
        uses: Rishabh510/Path-lister-action@1.0
      - name: ensure-conventional-commits
        uses: ohpensource/platform-cicd/actions/git/ensure-conventional-commits@8b63bf806e56c6fe7fd2cab93405fdf0f0921f8a
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF
