name: continuous-delivery-test
on: 
  push:
    branches: ["main"]
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: semver & changelog
        uses: ohpensource/platform-cicd/actions/git/generate-version-and-release-notes@0bbbf2b7e3212cc7586a1d44ce5e7eb2f1f5b40e
        with:
          user-email: "github-svc@ohpen.com"
          user-name: "GitHub Actions"
