name: continuous-delivery-test
on: 
  push:
    branches: ["main"]
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: semver & changelog
        uses: ohpensource/platform-cicd/actions/git/generate-version-and-release-notes@ea53d4a7e518d941153b42ca1f734a9db546d360
        with:
          user-email: "github-svc@ohpen.com"
          user-name: "GitHub Actions"
